# Generated by Django 5.1.7 on 2025-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('nfc', 'NFC Card'), ('qr', 'QR')], default='qr', max_length=3),
        ),
    ]
