# Generated by Django 5.1.7 on 2025-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('nfc', 'NFC Card'), ('qr', 'QR'), ('unk', 'Unknown')], default='qr', max_length=3),
        ),
    ]
