# Generated by Django 5.2 on 2025-06-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_driver_assigned_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="assigned_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver",
                to="payments.device",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="assigned_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="payments.route",
            ),
        ),
        migrations.DeleteModel(
            name="DriverAssignment",
        ),
    ]
