# Generated by Django 5.2 on 2025-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_driver_assigned_device_driver_assigned_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
