# Generated by Django 5.2 on 2025-06-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_trip_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("min_lat", models.FloatField()),
                ("min_lng", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("max_lng", models.FloatField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="payments.route",
                    ),
                ),
            ],
        ),
    ]
