# Generated by Django 5.2 on 2025-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_stop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="end_latitude",
        ),
        migrations.RemoveField(
            model_name="route",
            name="end_longitude",
        ),
        migrations.RemoveField(
            model_name="route",
            name="end_stop_name",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_latitude",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_longitude",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_stop_name",
        ),
        migrations.AlterField(
            model_name="stop",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
