# Generated by Django 5.2 on 2025-06-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0007_remove_route_end_latitude_remove_route_end_longitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="name",
        ),
    ]
