# Generated by Django 5.2 on 2025-06-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_trip_expected_passengers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="expected_passengers",
        ),
    ]
