"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import pathlib

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3m7hq^z)he5v+pnw53&=(x!cip=+pq3)gx!6+2-8kfu=^lmydy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'ahmed80800.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
    '192.168.1.8',
    '192.168.43.154',
    '127.0.0.1',
]

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'payments.auth.DriverJWTAuthentication',
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  )
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'utils',
    'payments',           # تطبيقك الخاص
    'rest_framework',     # لتسهيل بناء الـ API
    'corsheaders',        # للسماح بالطلبات من مصادر خارجية (CORS)
]

# السماح لجميع المصادر للطلبات الخارجية (يمكن ضبطه لاحقاً للأمان)
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # يجب أن يكون في البداية
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],  # مجلد القوالب العام
        'APP_DIRS': True,                    # يبحث تلقائيًا في كل app/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ahmed80800$PTP_ay',
#         'USER': 'ahmed80800',
#         'PASSWORD': 'AHMEDfarag1011',
#         'HOST': 'ahmed80800.mysql.pythonanywhere-services.com',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'









# ------------------ Aggregation settings ------------------

# ملفات الأكواد التي نريد تجميعها (مقارنة بـ BASE_DIR)
AGGREGATE_CODE_FILES = [
    # من مجلد payments
    'payments/admin.py',
    'payments/models.py',
    'payments/serializers.py',
    'payments/token_serializers.py',
    'payments/token_views.py',
    'payments/urls.py',
    'payments/views.py',

    # من مجلد myproject (الدليل الرئيسي للمشروع)
    'myproject/settings.py',
    'myproject/urls.py',
]

# مسار واسم الملف الناتج (سيُنشأ في جذر المشروع)
AGGREGATE_CODE_OUTPUT = BASE_DIR / 'all_code.txt'






LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'payments.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
